In [35]:
import pandas as pd
import requests
from datetime import datetime,timedelta,timezone
import yaml

In [3]:
URL = "https://api4.binance.com"
ENDPOINT = "/api/v3/aggTrades"

API = URL+ENDPOINT
print(API)

https://api4.binance.com/api/v3/aggTrades

In [67]:
start = int(datetime(2026,1,1,0,0,0,tzinfo=timezone.utc).timestamp()*1000)
end = int(datetime(2026,1,1,1,0,0,tzinfo=timezone.utc).timestamp()*1000)

In [73]:
start

1767225600000

In [30]:
datetime.utcfromtimestamp(end/1000)

/var/folders/rt/65wm9q4s2x1ccgrtn48cmx4h0000gn/T/ipykernel_978/2648891328.py:1: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  datetime.utcfromtimestamp(end/1000)

datetime.datetime(2026, 1, 1, 1, 0)

In [10]:
SYMBOL = "BTCUSDT"

params = {
    "symbol" : SYMBOL,
    "startTime": start,
    "endTime": end ,
    "limit": 1000
}

res = requests.get(API,params=params)
data = res.json()

In [12]:
pd.DataFrame(data)

,a,p,q,f,l,T,m,M
0,3800384934,87728.30000000,0.00006000,5723665621,5723665621,1767222000414,False,True
1,3800384935,87728.29000000,0.01000000,5723665622,5723665628,1767222000655,True,True
2,3800384936,87728.29000000,0.01181000,5723665629,5723665629,1767222000662,True,True
3,3800384937,87728.29000000,0.03419000,5723665630,5723665636,1767222000675,True,True
4,3800384938,87728.29000000,0.03092000,5723665637,5723665637,1767222000686,True,True
...,...,...,...,...,...,...,...,...
995,3800385929,87698.29000000,0.00029000,5723669372,5723669372,1767222209566,False,True
996,3800385930,87698.29000000,0.00160000,5723669373,5723669373,1767222210607,False,True
997,3800385931,87698.29000000,0.00011000,5723669374,5723669374,1767222210967,False,True
998,3800385932,87698.28000000,0.00006000,5723669375,5723669375,1767222211058,True,True
999,3800385933,87698.28000000,0.00059000,5723669376,5723669376,1767222211340,True,True

In [ ]:
lst = []
end_ = end
while start < end:
    
    params = {
        "symbol" : SYMBOL,
        "startTime": start,
        "endTime": end ,
        "limit": 1000
        }

    res = requests.get(API,params=params)
    data = res.json()
    if len(data) == 1000:
        end = (start+end)//2
        # print(f"Reducing to: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")
    else:
        print(f"Fetching: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")
        df = pd.DataFrame(data)
        if len(df) != 0:
            lst.append(df)
        start = end+1
        end = (end_ + start)//2
lst

/var/folders/rt/65wm9q4s2x1ccgrtn48cmx4h0000gn/T/ipykernel_978/1916109362.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  print(f"Fetching: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")

Fetching: 2026-01-01 00:00:00 - 2026-01-01 00:01:52
Fetching: 2026-01-01 00:01:52 - 2026-01-01 00:03:41
Fetching: 2026-01-01 00:03:41 - 2026-01-01 00:05:27
Fetching: 2026-01-01 00:05:27 - 2026-01-01 00:06:18
Fetching: 2026-01-01 00:06:18 - 2026-01-01 00:07:58
Fetching: 2026-01-01 00:07:58 - 2026-01-01 00:11:13
Fetching: 2026-01-01 00:11:13 - 2026-01-01 00:17:19
Fetching: 2026-01-01 00:17:19 - 2026-01-01 00:22:39
Fetching: 2026-01-01 00:22:39 - 2026-01-01 00:27:19
Fetching: 2026-01-01 00:27:19 - 2026-01-01 00:31:24
Fetching: 2026-01-01 00:31:24 - 2026-01-01 00:34:59
Fetching: 2026-01-01 00:34:59 - 2026-01-01 00:38:06
Fetching: 2026-01-01 00:38:06 - 2026-01-01 00:43:35
Fetching: 2026-01-01 00:43:35 - 2026-01-01 00:47:41
Fetching: 2026-01-01 00:47:41 - 2026-01-01 00:49:13
Fetching: 2026-01-01 00:49:13 - 2026-01-01 00:51:55
Fetching: 2026-01-01 00:51:55 - 2026-01-01 00:53:56
Fetching: 2026-01-01 00:53:56 - 2026-01-01 00:56:58
Fetching: 2026-01-01 00:56:58 - 2026-01-01 00:58:29
Fetching: 2026-01-01 00:58:29 - 2026-01-01 00:59:14
Fetching: 2026-01-01 00:59:14 - 2026-01-01 00:59:37
Fetching: 2026-01-01 00:59:37 - 2026-01-01 00:59:48
Fetching: 2026-01-01 00:59:48 - 2026-01-01 00:59:54
Fetching: 2026-01-01 00:59:54 - 2026-01-01 00:59:57
Fetching: 2026-01-01 00:59:57 - 2026-01-01 00:59:58
Fetching: 2026-01-01 00:59:58 - 2026-01-01 00:59:59

/var/folders/rt/65wm9q4s2x1ccgrtn48cmx4h0000gn/T/ipykernel_978/1916109362.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  print(f"Fetching: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")

Fetching: 2026-01-01 00:59:59 - 2026-01-01 00:59:59

/var/folders/rt/65wm9q4s2x1ccgrtn48cmx4h0000gn/T/ipykernel_978/1916109362.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  print(f"Fetching: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")

Fetching: 2026-01-01 00:59:59 - 2026-01-01 00:59:59

/var/folders/rt/65wm9q4s2x1ccgrtn48cmx4h0000gn/T/ipykernel_978/1916109362.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  print(f"Fetching: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")

Fetching: 2026-01-01 00:59:59 - 2026-01-01 00:59:59

/var/folders/rt/65wm9q4s2x1ccgrtn48cmx4h0000gn/T/ipykernel_978/1916109362.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  print(f"Fetching: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")

Fetching: 2026-01-01 00:59:59 - 2026-01-01 00:59:59

/var/folders/rt/65wm9q4s2x1ccgrtn48cmx4h0000gn/T/ipykernel_978/1916109362.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  print(f"Fetching: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")

Fetching: 2026-01-01 00:59:59 - 2026-01-01 00:59:59

/var/folders/rt/65wm9q4s2x1ccgrtn48cmx4h0000gn/T/ipykernel_978/1916109362.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  print(f"Fetching: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")

Fetching: 2026-01-01 00:59:59 - 2026-01-01 00:59:59
Fetching: 2026-01-01 00:59:59 - 2026-01-01 00:59:59
Fetching: 2026-01-01 00:59:59 - 2026-01-01 00:59:59

/var/folders/rt/65wm9q4s2x1ccgrtn48cmx4h0000gn/T/ipykernel_978/1916109362.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  print(f"Fetching: {datetime.utcfromtimestamp(start/1000).strftime("%Y-%m-%d %H:%M:%S")} - {datetime.utcfromtimestamp(end/1000).strftime("%Y-%m-%d %H:%M:%S")}")

[              a               p           q           f           l  \
 0    3800397495  87648.21000000  0.08185000  5723703861  5723703861
 1    3800397496  87648.22000000  0.00013000  5723703862  5723703862
 2    3800397497  87648.22000000  0.00023000  5723703863  5723703863
 3    3800397498  87648.22000000  0.01032000  5723703864  5723703864
 4    3800397499  87648.22000000  0.00206000  5723703865  5723703865
 ..          ...             ...         ...         ...         ...
 909  3800398404  87686.78000000  0.00011000  5723706420  5723706420
 910  3800398405  87686.79000000  0.00133000  5723706421  5723706421
 911  3800398406  87686.79000000  0.00135000  5723706422  5723706422
 912  3800398407  87686.79000000  0.00125000  5723706423  5723706423
 913  3800398408  87686.79000000  0.00073000  5723706424  5723706424

                  T      m     M
 0    1767225600039   True  True
 1    1767225600272  False  True
 2    1767225600276  False  True
 3    1767225600396  False  True
 4    1767225600401  False  True
 ..             ...    ...   ...
 909  1767225709861   True  True
 910  1767225710637  False  True
 911  1767225711334  False  True
 912  1767225711498  False  True
 913  1767225712251  False  True

 [914 rows x 8 columns],
               a               p           q           f           l  \
 0    3800398409  87686.79000000  0.00011000  5723706425  5723706425
 1    3800398410  87686.78000000  0.00050000  5723706426  5723706426
 2    3800398411  87686.78000000  0.00405000  5723706427  5723706427
 3    3800398412  87686.78000000  0.00125000  5723706428  5723706428
 4    3800398413  87686.79000000  0.00134000  5723706429  5723706429
 ..          ...             ...         ...         ...         ...
 431  3800398840  87689.94000000  0.00200000  5723707829  5723707829
 432  3800398841  87689.94000000  0.01200000  5723707830  5723707830
 433  3800398842  87689.94000000  0.00721000  5723707831  5723707831
 434  3800398843  87689.93000000  0.00174000  5723707832  5723707832
 435  3800398844  87689.93000000  0.00057000  5723707833  5723707833

                  T      m     M
 0    1767225712523  False  True
 1    1767225713335   True  True
 2    1767225713428   True  True
 3    1767225715434   True  True
 4    1767225715641  False  True
 ..             ...    ...   ...
 431  1767225819764  False  True
 432  1767225819771  False  True
 433  1767225820961  False  True
 434  1767225821361   True  True
 435  1767225821418   True  True

 [436 rows x 8 columns],
               a               p           q           f           l  \
 0    3800398845  87689.94000000  0.00570000  5723707834  5723707834
 1    3800398846  87689.93000000  0.00219000  5723707835  5723707835
 2    3800398847  87689.93000000  0.00051000  5723707836  5723707836
 3    3800398848  87689.93000000  0.00010000  5723707837  5723707837
 4    3800398849  87689.94000000  0.00228000  5723707838  5723707838
 ..          ...             ...         ...         ...         ...
 699  3800399544  87750.00000000  0.00921000  5723710261  5723710261
 700  3800399545  87750.00000000  0.02811000  5723710262  5723710262
 701  3800399546  87749.99000000  0.02811000  5723710263  5723710263
 702  3800399547  87749.99000000  0.01914000  5723710264  5723710264
 703  3800399548  87750.00000000  0.00123000  5723710265  5723710271

                  T      m     M
 0    1767225821711  False  True
 1    1767225821760   True  True
 2    1767225821846   True  True
 3    1767225823260   True  True
 4    1767225823495  False  True
 ..             ...    ...   ...
 699  1767225926090  False  True
 700  1767225926158  False  True
 701  1767225926338   True  True
 702  1767225926558   True  True
 703  1767225926936  False  True

 [704 rows x 8 columns],
               a               p           q           f           l  \
 0    3800399549  87750.00000000  0.00015000  5723710272  5723710272
 1    3800399550  87749.99000000  0.00307000  5723710273  5723710273
 2    3800399551  87750.00000000  0.01140000  5723710274  5723710274
 3    3800399552  87750.00000000  0.59022000  5723710275  5723710319
 4    3800399553  87750.01000000  0.00141000  5723710320  5723710341
 ..          ...             ...         ...         ...         ...
 989  3800400538  87750.45000000  0.00018000  5723713148  5723713150
 990  3800400539  87750.44000000  0.00368000  5723713151  5723713151
 991  3800400540  87750.44000000  0.00021000  5723713152  5723713155
 992  3800400541  87750.45000000  0.00010000  5723713156  5723713156
 993  3800400542  87750.44000000  0.00012000  5723713157  5723713158

                  T      m     M
 0    1767225927513  False  True
 1    1767225927550   True  True
 2    1767225927796  False  True
 3    1767225927796  False  True
 4    1767225927796  False  True
 ..             ...    ...   ...
 989  1767225975611   True  True
 990  1767225975611   True  True
 991  1767225975824   True  True
 992  1767225977242  False  True
 993  1767225977337   True  True

 [994 rows x 8 columns],
               a               p           q           f           l  \
 0    3800400543  87750.44000000  0.00060000  5723713159  5723713167
 1    3800400544  87750.45000000  0.00056000  5723713168  5723713168
 2    3800400545  87750.45000000  0.00082000  5723713169  5723713169
 3    3800400546  87750.44000000  0.00199000  5723713170  5723713174
 4    3800400547  87750.43000000  0.00398000  5723713175  5723713175
 ..          ...             ...         ...         ...         ...
 859  3800401402  87739.99000000  0.00039000  5723716188  5723716188
 860  3800401403  87740.00000000  0.00300000  5723716189  5723716189
 861  3800401404  87739.99000000  0.00077000  5723716190  5723716190
 862  3800401405  87739.99000000  0.00058000  5723716191  5723716198
 863  3800401406  87739.99000000  0.01360000  5723716199  5723716213

                  T      m     M
 0    1767225978598   True  True
 1    1767225978643  False  True
 2    1767225978728  False  True
 3    1767225980232   True  True
 4    1767225980232   True  True
 ..             ...    ...   ...
 859  1767226078027   True  True
 860  1767226078305  False  True
 861  1767226078460   True  True
 862  1767226078745   True  True
 863  1767226078829   True  True

 [864 rows x 8 columns],
               a               p           q           f           l  \
 0    3800401407  87740.00000000  0.00056000  5723716214  5723716214
 1    3800401408  87740.00000000  0.00184000  5723716215  5723716215
 2    3800401409  87739.99000000  0.00190000  5723716216  5723716216
 3    3800401410  87739.99000000  0.00093000  5723716217  5723716217
 4    3800401411  87739.99000000  0.00040000  5723716218  5723716218
 ..          ...             ...         ...         ...         ...
 957  3800402364  87754.06000000  0.00031000  5723719514  5723719514
 958  3800402365  87754.06000000  0.00011000  5723719515  5723719515
 959  3800402366  87754.06000000  0.00010000  5723719516  5723719516
 960  3800402367  87754.07000000  0.00090000  5723719517  5723719517
 961  3800402368  87754.06000000  0.00026000  5723719518  5723719519

                  T      m     M
 0    1767226079680  False  True
 1    1767226080166  False  True
 2    1767226080285   True  True
 3    1767226080419   True  True
 4    1767226080881   True  True
 ..             ...    ...   ...
 957  1767226271780   True  True
 958  1767226271929   True  True
 959  1767226272521   True  True
 960  1767226272977  False  True
 961  1767226273693   True  True

 [962 rows x 8 columns],
               a               p           q           f           l  \
 0    3800402369  87754.07000000  0.00012000  5723719520  5723719520
 1    3800402370  87754.07000000  0.00012000  5723719521  5723719521
 2    3800402371  87754.07000000  0.00010000  5723719522  5723719522
 3    3800402372  87754.07000000  0.00040000  5723719523  5723719523
 4    3800402373  87754.06000000  0.00040000  5723719524  5723719524
 ..          ...             ...         ...         ...         ...
 968  3800403337  87750.58000000  0.00006000  5723722442  5723722442
 969  3800403338  87750.58000000  0.06700000  5723722443  5723722445
 970  3800403339  87750.58000000  0.05698000  5723722446  5723722446
 971  3800403340  87750.57000000  0.00016000  5723722447  5723722447
 972  3800403341  87750.57000000  0.00006000  5723722448  5723722448

                  T      m     M
 0    1767226274480  False  True
 1    1767226275169  False  True
 2    1767226275836  False  True
 3    1767226277703  False  True
 4    1767226277903   True  True
 ..             ...    ...   ...
 968  1767226635543  False  True
 969  1767226636680  False  True
 970  1767226638714  False  True
 971  1767226639013   True  True
 972  1767226639709   True  True

 [973 rows x 8 columns],
               a               p           q           f           l  \
 0    3800403342  87750.58000000  0.00037000  5723722449  5723722449
 1    3800403343  87750.58000000  0.00009000  5723722450  5723722450
 2    3800403344  87750.58000000  0.00020000  5723722451  5723722451
 3    3800403345  87750.58000000  0.00020000  5723722452  5723722452
 4    3800403346  87750.58000000  0.00570000  5723722453  5723722453
 ..          ...             ...         ...         ...         ...
 763  3800404105  87768.34000000  0.00045000  5723724187  5723724187
 764  3800404106  87768.33000000  0.00006000  5723724188  5723724188
 765  3800404107  87768.33000000  0.00284000  5723724189  5723724189
 766  3800404108  87768.34000000  0.00569000  5723724190  5723724190
 767  3800404109  87768.33000000  0.00031000  5723724191  5723724191

                  T      m     M
 0    1767226639732  False  True
 1    1767226639796  False  True
 2    1767226640070  False  True
 3    1767226640070  False  True
 4    1767226640500  False  True
 ..             ...    ...   ...
 763  1767226952981  False  True
 764  1767226954416   True  True
 765  1767226957135   True  True
 766  1767226958230  False  True
 767  1767226958481   True  True

 [768 rows x 8 columns],
               a               p           q           f           l  \
 0    3800404110  87768.34000000  0.00011000  5723724192  5723724192
 1    3800404111  87768.33000000  0.00079000  5723724193  5723724193
 2    3800404112  87768.34000000  0.00007000  5723724194  5723724194
 3    3800404113  87768.34000000  0.00013000  5723724195  5723724195
 4    3800404114  87768.33000000  0.00011000  5723724196  5723724196
 ..          ...             ...         ...         ...         ...
 707  3800404817  87768.51000000  0.00235000  5723726130  5723726130
 708  3800404818  87768.51000000  0.00296000  5723726131  5723726131
 709  3800404819  87768.50000000  0.00006000  5723726132  5723726132
 710  3800404820  87768.51000000  0.00015000  5723726133  5723726133
 711  3800404821  87768.51000000  0.00101000  5723726134  5723726134

                  T      m     M
 0    1767226960343  False  True
 1    1767226962750   True  True
 2    1767226962945  False  True
 3    1767226962990  False  True
 4    1767226963231   True  True
 ..             ...    ...   ...
 707  1767227238830  False  True
 708  1767227239104  False  True
 709  1767227239251   True  True
 710  1767227239538  False  True
 711  1767227239697  False  True

 [712 rows x 8 columns],
               a               p           q           f           l  \
 0    3800404822  87768.50000000  0.00049000  5723726135  5723726135
 1    3800404823  87768.51000000  0.01000000  5723726136  5723726136
 2    3800404824  87768.51000000  0.00006000  5723726137  5723726137
 3    3800404825  87768.51000000  0.04000000  5723726138  5723726138
 4    3800404826  87768.51000000  0.00010000  5723726139  5723726139
 ..          ...             ...         ...         ...         ...
 724  3800405546  87764.40000000  0.00015000  5723727724  5723727724
 725  3800405547  87764.40000000  0.00005000  5723727725  5723727725
 726  3800405548  87764.39000000  0.00013000  5723727726  5723727726
 727  3800405549  87764.40000000  0.00015000  5723727727  5723727727
 728  3800405550  87764.40000000  0.00014000  5723727728  5723727728

                  T      m     M
 0    1767227239845   True  True
 1    1767227240530  False  True
 2    1767227241378  False  True
 3    1767227241831  False  True
 4    1767227242014  False  True
 ..             ...    ...   ...
 724  1767227482597  False  True
 725  1767227482821  False  True
 726  1767227483632   True  True
 727  1767227483884  False  True
 728  1767227483991  False  True

 [729 rows x 8 columns],
               a               p           q           f           l  \
 0    3800405551  87764.40000000  0.00015000  5723727729  5723727729
 1    3800405552  87764.39000000  0.00014000  5723727730  5723727730
 2    3800405553  87764.39000000  0.00416000  5723727731  5723727731
 3    3800405554  87764.40000000  0.00010000  5723727732  5723727732
 4    3800405555  87764.40000000  0.00015000  5723727733  5723727733
 ..          ...             ...         ...         ...         ...
 905  3800406456  87748.78000000  0.00015000  5723730038  5723730038
 906  3800406457  87748.79000000  0.00031000  5723730039  5723730039
 907  3800406458  87748.79000000  0.00017000  5723730040  5723730040
 908  3800406459  87748.79000000  0.00088000  5723730041  5723730041
 909  3800406460  87748.78000000  0.00056000  5723730042  5723730042

                  T      m     M
 0    1767227485145  False  True
 1    1767227485641   True  True
 2    1767227485904   True  True
 3    1767227486881  False  True
 4    1767227486886  False  True
 ..             ...    ...   ...
 905  1767227697577   True  True
 906  1767227697778  False  True
 907  1767227698261  False  True
 908  1767227698367  False  True
 909  1767227698651   True  True

 [910 rows x 8 columns],
               a               p           q           f           l  \
 0    3800406461  87748.79000000  0.00015000  5723730043  5723730043
 1    3800406462  87748.79000000  0.00064000  5723730044  5723730044
 2    3800406463  87748.78000000  0.00031000  5723730045  5723730045
 3    3800406464  87748.79000000  0.00102000  5723730046  5723730046
 4    3800406465  87748.79000000  0.00152000  5723730047  5723730047
 ..          ...             ...         ...         ...         ...
 710  3800407171  87733.99000000  0.00449000  5723732067  5723732067
 711  3800407172  87733.98000000  0.00057000  5723732068  5723732068
 712  3800407173  87733.99000000  0.00007000  5723732069  5723732069
 713  3800407174  87733.98000000  0.00011000  5723732070  5723732070
 714  3800407175  87733.99000000  0.00053000  5723732071  5723732071

                  T      m     M
 0    1767227699224  False  True
 1    1767227699420  False  True
 2    1767227700110   True  True
 3    1767227700370  False  True
 4    1767227700434  False  True
 ..             ...    ...   ...
 710  1767227883768  False  True
 711  1767227884412   True  True
 712  1767227884625  False  True
 713  1767227884681   True  True
 714  1767227885142  False  True

 [715 rows x 8 columns],
               a               p           q           f           l  \
 0    3800407176  87733.99000000  0.00007000  5723732072  5723732072
 1    3800407177  87733.99000000  0.01099000  5723732073  5723732073
 2    3800407178  87733.99000000  0.00038000  5723732074  5723732074
 3    3800407179  87733.98000000  0.00023000  5723732075  5723732075
 4    3800407180  87733.98000000  0.00725000  5723732076  5723732076
 ..          ...             ...         ...         ...         ...
 757  3800407933  87758.61000000  0.00052000  5723734055  5723734055
 758  3800407934  87758.62000000  0.00056000  5723734056  5723734057
 759  3800407935  87758.61000000  0.00056000  5723734058  5723734058
 760  3800407936  87758.62000000  0.02033000  5723734059  5723734059
 761  3800407937  87758.62000000  0.00093000  5723734060  5723734060

                  T      m     M
 0    1767227887558  False  True
 1    1767227888251  False  True
 2    1767227888741  False  True
 3    1767227889772   True  True
 4    1767227892070   True  True
 ..             ...    ...   ...
 757  1767228208725   True  True
 758  1767228209379  False  True
 759  1767228211238   True  True
 760  1767228214439  False  True
 761  1767228214577  False  True

 [762 rows x 8 columns],
               a               p           q           f           l  \
 0    3800407938  87758.62000000  0.00027000  5723734061  5723734061
 1    3800407939  87758.61000000  0.00110000  5723734062  5723734062
 2    3800407940  87758.62000000  0.00112000  5723734063  5723734063
 3    3800407941  87758.62000000  0.00043000  5723734064  5723734064
 4    3800407942  87758.62000000  0.00296000  5723734065  5723734065
 ..          ...             ...         ...         ...         ...
 538  3800408476  87748.88000000  0.00014000  5723734940  5723734940
 539  3800408477  87748.88000000  0.00089000  5723734941  5723734941
 540  3800408478  87748.89000000  0.00114000  5723734942  5723734942
 541  3800408479  87748.88000000  0.00044000  5723734943  5723734943
 542  3800408480  87748.88000000  0.00241000  5723734944  5723734944

                  T      m     M
 0    1767228215968  False  True
 1    1767228216082   True  True
 2    1767228216086  False  True
 3    1767228216087  False  True
 4    1767228216430  False  True
 ..             ...    ...   ...
 538  1767228459058   True  True
 539  1767228459253   True  True
 540  1767228459737  False  True
 541  1767228459871   True  True
 542  1767228461308   True  True

 [543 rows x 8 columns],
               a               p           q           f           l  \
 0    3800408481  87748.88000000  0.00095000  5723734945  5723734945
 1    3800408482  87748.89000000  0.00014000  5723734946  5723734946
 2    3800408483  87748.89000000  0.00063000  5723734947  5723734947
 3    3800408484  87748.89000000  0.00380000  5723734948  5723734948
 4    3800408485  87748.89000000  0.00029000  5723734949  5723734949
 ..          ...             ...         ...         ...         ...
 672  3800409153  87782.00000000  0.00200000  5723737897  5723737905
 673  3800409154  87782.00000000  0.00200000  5723737906  5723737906
 674  3800409155  87782.00000000  0.00965000  5723737907  5723737926
 675  3800409156  87781.99000000  0.00079000  5723737927  5723737927
 676  3800409157  87782.00000000  0.00012000  5723737928  5723737929

                  T      m     M
 0    1767228462235   True  True
 1    1767228462497  False  True
 2    1767228463303  False  True
 3    1767228463308  False  True
 4    1767228463444  False  True
 ..             ...    ...   ...
 672  1767228552645  False  True
 673  1767228552650  False  True
 674  1767228553115  False  True
 675  1767228553224   True  True
 676  1767228553539  False  True

 [677 rows x 8 columns],
               a               p           q           f           l  \
 0    3800409158  87782.00000000  0.00012000  5723737930  5723737931
 1    3800409159  87782.00000000  0.00200000  5723737932  5723737938
 2    3800409160  87782.00000000  0.00200000  5723737939  5723737939
 3    3800409161  87782.00000000  0.00200000  5723737940  5723737940
 4    3800409162  87782.00000000  0.00012000  5723737941  5723737941
 ..          ...             ...         ...         ...         ...
 708  3800409866  87810.49000000  0.00682000  5723741067  5723741078
 709  3800409867  87810.48000000  0.00012000  5723741079  5723741079
 710  3800409868  87810.48000000  0.00306000  5723741080  5723741080
 711  3800409869  87810.49000000  0.00028000  5723741081  5723741081
 712  3800409870  87810.48000000  0.00332000  5723741082  5723741082

                  T      m     M
 0    1767228554445  False  True
 1    1767228556638  False  True
 2    1767228556641  False  True
 3    1767228556645  False  True
 4    1767228557540  False  True
 ..             ...    ...   ...
 708  1767228713412  False  True
 709  1767228713739   True  True
 710  1767228714543   True  True

In [ ]:
df_raw = pd.concat(lst,axis =0).reset_index(drop=True)
df_raw

,a,p,q,f,l,T,m,M
0,3800397495,87648.21000000,0.08185000,5723703861,5723703861,1767225600039,True,True
1,3800397496,87648.22000000,0.00013000,5723703862,5723703862,1767225600272,False,True
2,3800397497,87648.22000000,0.00023000,5723703863,5723703863,1767225600276,False,True
3,3800397498,87648.22000000,0.01032000,5723703864,5723703864,1767225600396,False,True
4,3800397499,87648.22000000,0.00206000,5723703865,5723703865,1767225600401,False,True
...,...,...,...,...,...,...,...,...
2,3800412145,87809.23000000,0.00020000,5723748638,5723748638,1767229196251,True,True
3,3800412146,87809.23000000,0.00007000,5723748639,5723748639,1767229196587,True,True
0,3800412147,87809.24000000,0.00034000,5723748640,5723748640,1767229197182,False,True
1,3800412148,87809.24000000,0.00011000,5723748641,5723748641,1767229198097,False,True
0,3800412149,87809.23000000,0.00056000,5723748642,5723748642,1767229199980,True,True

In [38]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14655 entries, 0 to 0
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       14655 non-null  int64
 1   p       14655 non-null  object
 2   q       14655 non-null  object
 3   f       14655 non-null  int64
 4   l       14655 non-null  int64
 5   T       14655 non-null  int64
 6   m       14655 non-null  bool
 7   M       14655 non-null  bool
dtypes: bool(2), int64(4), object(2)
memory usage: 830.1+ KB

In [62]:
with open("../config/schema.yaml","r") as f:
    config = yaml.safe_load(f)
config

{'data': {'columns': {'a': 'trade_id',
   'p': 'price',
   'q': 'quantity',
   'f': 'first_trade_id',
   'l': 'last_trade_id',
   'T': 'timestamp_utc',
   'm': 'is_maker',
   'M': 'best_match'},
  'dtypes': {'a': 'int64',
   'p': 'double',
   'q': 'double',
   'f': 'int64',
   'l': 'int64',
   'T': 'int64',
   'm': 'bool',
   'M': 'bool'}}}

In [64]:
config['data']['columns'].items()

dict_items([('a', 'trade_id'), ('p', 'price'), ('q', 'quantity'), ('f', 'first_trade_id'), ('l', 'last_trade_id'), ('T', 'timestamp_utc'), ('m', 'is_maker'), ('M', 'best_match')])

In [65]:
def process_dataframe(df,config):
    for col , dt in config['data']['dtypes'].items():
        df[col] = df[col].astype(dt)
    
    df = df.rename(columns = config['data']['columns'])
    return df

In [66]:
df_transform = process_dataframe(df_raw,config)
df_transform

,trade_id,price,quantity,first_trade_id,last_trade_id,timestamp_utc,is_maker,best_match
0,3800397495,87648.21,0.08185,5723703861,5723703861,1767225600039,True,True
1,3800397496,87648.22,0.00013,5723703862,5723703862,1767225600272,False,True
2,3800397497,87648.22,0.00023,5723703863,5723703863,1767225600276,False,True
3,3800397498,87648.22,0.01032,5723703864,5723703864,1767225600396,False,True
4,3800397499,87648.22,0.00206,5723703865,5723703865,1767225600401,False,True
...,...,...,...,...,...,...,...,...
2,3800412145,87809.23,0.00020,5723748638,5723748638,1767229196251,True,True
3,3800412146,87809.23,0.00007,5723748639,5723748639,1767229196587,True,True
0,3800412147,87809.24,0.00034,5723748640,5723748640,1767229197182,False,True
1,3800412148,87809.24,0.00011,5723748641,5723748641,1767229198097,False,True
0,3800412149,87809.23,0.00056,5723748642,5723748642,1767229199980,True,True

In [69]:
df_transform['timestamp_utc'].max()

np.int64(1767229199980)

In [71]:
with open("../data/params.txt","w") as f:
    f.write(str(df_transform['timestamp_utc'].max()))

In [72]:
with open("../data/params.txt","r") as f:
    start_test = int(f.read())
start_test

1767229199980

In [78]:
from databricks import sql